ignoreRaw: /?mock_.*|.local/.*
findNames: "*.go,*.sh"
commentSh: "# "
commentGo: "// "
header: "Copyright 2024 Raphael Thomazella. All rights reserved.\n
  Use of this source code is governed by the BSD-3-Clause\n
  license that can be found in the LICENSE file and online\n
  at https://opensource.org/license/BSD-3-clause."
