root_go_mod:
  - go.mod
  - go.sum
cmd_go_mod:
  - cmd/go.mod
  - cmd/go.sum
any_go_mod:
  - "**/go.mod"
  - "**/go.sum"
config:
  - "**/*.yml"
  - "**/*.json"
doc:
  - "**/*.md"
shell:
  - sh/**.sh
clock:
  - clock/**.go
  - clock/go.mod
  - clock/go.sum
httpmisc:
  - httpmisc/**.go
  - httpmisc/go.mod
  - httpmisc/go.sum
hue:
  - hue/**.go
  - hue/go.mod
  - hue/go.sum
identifier:
  - identifier/**.go
  - identifier/go.mod
  - identifier/go.sum
jsonutil:
  - jsonutil/**.go
  - jsonutil/go.mod
  - jsonutil/go.sum
logging:
  - logging/**.go
  - logging/go.mod
  - logging/go.sum
misc:
  - misc/**.go
  - misc/go.mod
  - misc/go.sum
any_code:
  - "**/*.go"
  - "**/*.sh"
cmd_t0copyright:
  - cmd/t0copyright/**.go
cmd_gen_go_work:
  - cmd/gengowork/**.go
cmd_t0filer:
  - cmd/t0filer/**.go
cmd_t0changelog:
  - cmd/t0changelog/**.go
