# see https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

run:
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - nilerr
    - govet
    - gosec
    - importas
    - nilnil
    - paralleltest
    - tparallel
    - gocritic
    - gocyclo
    - lll
    - nolintlint
    - staticcheck
    - stylecheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - bodyclose
    - intrange
    - contextcheck
    - errcheck
    - errchkjson
    - errname
    - exhaustive
    - exportloopref
    - makezero
    - mirror
    - noctx
    - perfsprint
    - sloglint
    - tenv
    - thelper
    - varnamelen
    - wastedassign
    - wrapcheck

  disable:
    - gofmt # using gofumpt

  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  fast: true

linters-settings:
  govet:
    enable-all: true

  gosec:
    exclude-generated: true

  importas:
    no-unaliased: true
    alias:
      - pkg: example.dev/serving/pkg/apis/v1
        alias: examplev1

  paralleltest:
    ignore-missing: false
    ignore-missing-subtests: true

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint

  gocyclo:
    min-complexity: 15

  lll:
    line-length: 140

  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true

  exhaustive:
    check:
      - switch
      - map

  depguard:
    rules:
      main:
        list-mode: lax
        deny:
          - pkg: "github.com/example/example"
            desc: cannot be imported

  mnd:
    ignored-functions:
      - '^misc\.Seconds'
      - '^misc\.Minutes'
      - '^misc\.Hours'
      - '^misc\.Days'
      - '^(wg|wait|waitGroup)\.Add'
      - "^make"
      - "^os.OpenFile"

  funlen:
    ignore-comments: true

  varnamelen:
    ignore-decls:
      - i int
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true

  # can be removed after updates if there are no warnings
  errcheck:
    ignore: ""

  wrapcheck:
    ignorePackageGlobs:
      - golang.org/x/sync/*
