# see main.go task type
# <variables> are replaced by some value
# see main.go const section for variables

version: 0.2.0
tasks:
  - name: build
    package: true
    env:
      - MOD_PATH=<package>
      - HOME=<inherit>
      - PATH=<inherit>
      - BASH_ENV=./sh/lib/lib.sh
    exec:
      - ./sh/workflows/module_pr/build.sh
  - name: lint
    package: true
    exec:
      - "golangci-lint run --timeout 10s --print-issued-lines=false"
  - name: go-lint-fix
    package: true
    env:
      - HOME=<inherit>
      - PATH=<inherit>
      - BASH_ENV=./sh/lib/lib.sh
    exec:
      - "./sh/lib/go/lint_fix.sh <package>"
  - name: format
    package: true
    exec:
      - gofumpt -l -w
      - prettier --write <package>/**/*.yml
  - name: test
    package: true
    env:
      - CACHE=true
      - GITHUB_OUTPUT=/dev/null
      - COVERAGE_FILE=coverage.out
      - MOD_PATH=<package>
      - PATH=<inherit>
      - HOME=<inherit>
      - BASH_ENV=./sh/lib/lib.sh
    exec:
      - ./sh/workflows/module_pr/test_pretty.sh
  - name: format-configs
    exec:
      - "prettier --write ./**/*{.yml,.json}"
  - name: generate-mocks
    env:
      - PATH=<inherit>
      - HOME=<inherit>
      - BASH_ENV=./sh/lib/lib.sh
    exec:
      - ./sh/lib/go/generate_mocks.sh
  - name: spellcheck
    exec:
      - "cspell --gitignore ."
  - name: setup
    env:
      - HOME=<inherit>
      - PATH=<inherit>
      - NVM_DIR=<inherit>
      - BASH_ENV=./sh/lib/lib.sh
    exec:
      - ./sh/setup.sh
  - name: generate-go-work
    env:
      - PATH=<inherit>
      - HOME=<inherit>
      - T0_COLOR=<inherit>
      - T0_LOGLEVEL=<inherit>
    exec:
      - go run cmd/gengowork/main.go
  - name: new-module
    env:
      - PATH=<inherit>
      - HOME=<inherit>
      - BASH_ENV=./sh/lib/lib.sh
    exec:
      - ./sh/new_module.sh
  - name: copyright-fix-go
    env:
      - PATH=<inherit>
      - HOME=<inherit>
      - T0_COLOR=<inherit>
      - T0_LOGLEVEL=<inherit>
    exec:
      - go run cmd/t0copyright/main.go -check *.go -fix -comment //<space>
  - name: copyright-fix-sh
    env:
      - PATH=<inherit>
      - HOME=<inherit>
      - T0_COLOR=<inherit>
      - T0_LOGLEVEL=<inherit>
    exec:
      - go run cmd/t0copyright/main.go -check *.sh -fix -comment \#<space> -shebang
