$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: en
allowCompoundWords: true
maxNumberOfProblems: 7
dictionaries:
  - en-US
  - bash
  - docker
  - filetypes
  - fullstack
  - golang
  - k8s
  - lorem-ipsum
  - softwareTerms
  - computing-acronyms
words:
  - alnum
  - bellynha
  - busa
  - cipush
  - cmds
  - commitlintrc
  - cweill
  - davecgh
  - debg
  - erro
  - fatih
  - fatl
  - generatevscodetasks
  - gengowork
  - genvscodetasks
  - gger
  - gocritic
  - godotenv
  - gofmt
  - gofumpt
  - goimports
  - goinstall
  - golangci
  - gomodifytags
  - gopkgs
  - gopls
  - gorun
  - gosec
  - gotestfmt
  - gotests
  - govet
  - gsed
  - haya
  - honnef
  - httpflush
  - ifaceassert
  - iname
  - inpackage
  - inplace
  - joho
  - logg
  - maintidx
  - meepo
  - menlo
  - msgln
  - mvdan
  - nocasematch
  - noctx
  - nolint
  - nolintlint
  - nower
  - objx
  - ogger
  - pmezard
  - ramya
  - ribeiro
  - samber
  - scandir
  - seqs
  - shellcheck
  - shfmt
  - stretchr
  - tcodes
  - tcodes0
  - thom
  - thomazella
  - tparallel
  - unappend
  - unmarshaled
  - unmarshalling
  - unmarshals
  - uudashr
  - wrapf
  - xerrors
