$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: en
allowCompoundWords: true
maxNumberOfProblems: 7
dictionaries:
  - en-US
  - bash
  - docker
  - filetypes
  - fullstack
  - golang
  - k8s
  - lorem-ipsum
  - softwareTerms
  - computing-acronyms
words:
  - alnum
  - bellynha
  - Cmds
  - commitlintrc
  - DEBG
  - erro
  - FATL
  - godotenv
  - gofmt
  - gofumpt
  - goimports
  - goinstall
  - golangci
  - gomodifytags
  - gopkgs
  - gopls
  - gosec
  - gotestfmt
  - gotests
  - govet
  - gsed
  - httpflush
  - ifaceassert
  - iname
  - inpackage
  - inplace
  - maintidx
  - msgln
  - nocasematch
  - scandir
  - Seqs
  - SHELLCHECK
  - SHFMT
  - stretchr
  - tcodes
  - tcodes0
  - Thomazella
  - tparallel
  - Unappend
  - unmarshalling
  - unmarshals
