#! /usr/bin/env bash

### options, imports, mocks ###

set -euo pipefail
shopt -s globstar
# shellcheck disable=SC1091
source "$PWD/src/sh/lib.sh"

### vars and functions ###

mockeryGeneratedRegex="generated by mockery (v[0-9]+\.[0-9]+\.[0-9]+)"

saveMocksVersion() {
  sampleMockFile=$(find src -maxdepth 2 -type f -name 'mock*.go' | head -1)
  firstLine=$(head -1 "$sampleMockFile")

  if ! [[ $firstLine =~ $mockeryGeneratedRegex ]]; then
    msgExit "failed to parse mockery version from $sampleMockFile using regex $mockeryGeneratedRegex"
  fi

  printf %b "${BASH_REMATCH[1]}\n" >.mockery-version
}

stripVersion() {
  sed -Ei "s/$mockeryGeneratedRegex/generated by mockery/" src/**/mock*.go
}

renameExpect() {
  sed -Ei "s/EXPECT/Expect/" src/**/mock*.go
}

### validation, input handling ###

### script ###

mockery
saveMocksVersion
stripVersion
renameExpect
