version: 0.2.0
replace:
  feat: Features
  fix: Bug Fixes
  perf: Performance
  refactor: Improvements
  docs: Documentation
  build: Build
  ci: CI
  revert: Revert
  style: Styling
  test: Tests
  misc: Other
  chore: Other
