# unmarshaled into cmd/runner/main.go task type
- name: build
  module: true
  inputs: 2
  env:
    - MOD_PATH=<module>
    - HOME=<inherit>
    - PATH=<inherit>
  exec:
    - ./sh/workflows/module-pr/build.sh

- name: lint
  module: true
  inputs: 2
  exec:
    - "golangci-lint run --timeout 10s --print-issued-lines=false"

- name: format
  module: true
  inputs: 1
  exec:
    - "gofumpt -l -w"
    - "prettier --write <module>/**/*{.yml,.yaml,.json}"

- name: test
  module: true
  inputs: 1
  env:
    - CACHE=true
    - GITHUB_OUTPUT=/dev/null
    - COVERAGE_FILE=coverage.out
    - MOD_PATH=<module>
    - PATH=<inherit>
    - HOME=<inherit>
  exec:
    - ./sh/workflows/module-pr/test-pretty.sh

- name: ci
  needs: "<git-clean>, <online>"
  inputs: 1
  exec:
    - ./sh/ci.sh

- name: format-configs
  exec:
    - "prettier --write ./**/*{.yml,.yaml,.json}"

- name: generate-mocks
  exec:
    - ./sh/generate-mocks.sh

- name: spellcheck
  exec:
    - "cspell --gitignore ."

- name: setup
  exec:
    - ./sh/setup.sh

- name: generate-go-work
  env:
    - PATH=<inherit>
    - HOME=<inherit>
    - CMD_COLOR=<inherit>
    - CMD_LOGLEVEL=<inherit>
  exec:
    - go run cmd/gengowork/main.go

- name: new-module
  inputs: 1
  exec:
    - ./sh/new-module.sh

- name: generate-vscode-tasks
  env:
    - PATH=<inherit>
    - HOME=<inherit>
    - CMD_COLOR=<inherit>
    - CMD_LOGLEVEL=<inherit>
  exec:
    - "go run cmd/genvscodetasks/main.go -module-commands <task-module-names> -repo-commands <task-not-module-names>"

- name: copyright
  env:
    - PATH=<inherit>
    - HOME=<inherit>
    - CMD_COLOR=<inherit>
    - CMD_LOGLEVEL=<inherit>
  exec:
    - "go run cmd/copyright/main.go"
