# unmarshaled into cmd/run/main.go task type
- name: build
  kind: 1 # module
  inputs: 1
  exec:
    - ./sh/workflows/module-pr/build.sh

- name: lint
  kind: 1
  inputs: 1
  exec:
    - "golangci-lint run --timeout 10s --print-issued-lines=false"

- name: format
  kind: 1
  inputs: 1
  exec:
    - "gofumpt -l -w"
    - "prettier --write ./**/*{.yml,.yaml,.json}"

- name: lint-fix
  kind: 1
  inputs: 1
  exec:
    - ./sh/lint-fix.sh
    - "golangci-lint run --timeout 10s --print-issued-lines=false --fix"

- name: test
  kind: 1
  inputs: 1
  exec:
    - ./sh/workflows/module-pr/test-pretty.sh
  env:
    CACHE: true
    GITHUB_OUTPUT: /dev/null

- name: ci
  kind: 2 # repo
  needs: "git-clean, online"
  exec:
    - ./sh/ci.sh

- name: ci-push
  kind: 2
  needs: "git-clean, online"
  exec:
    - "./sh/ci.sh push"

- name: coverage
  kind: 2
  exec:
    - ./sh/coverage.sh

- name: format-configs
  kind: 2
  exec:
    - "prettier --write ./**/*{.yml,.yaml,.json}"

- name: generate-mocks
  kind: 2
  exec:
    - ./sh/generate-mocks.sh

- name: spellcheck-docs
  kind: 2
  exec:
    - "cspell --gitignore ./**/*.md"

- name: setup
  kind: 2
  exec:
    - ./sh/setup.sh

- name: generate-go-work
  kind: 2
  exec:
    - go run cmd/gengowork/main.go

- name: new-module
  kind: 2
  inputs: 1
  exec:
    - ./sh/new-module.sh

- name: generate-vscode-tasks
  kind: 2
  works: no
  exec:
    - "go run cmd/genvscodetasks/main.go"

- name: copyright
  kind: 2
  exec:
    - "go run cmd/copyright/main.go"
