# unmarshaled into cmd/run/main.go task type
- name: build
  module: true
  env:
    - MOD_PATH=<module>
    - HOME=<inherit>
    - PATH=<inherit>
  exec:
    - ./sh/workflows/module-pr/build.sh

- name: lint
  module: true
  exec:
    - "golangci-lint run --timeout 10s --print-issued-lines=false"

- name: format
  module: true
  exec:
    - "gofumpt -l -w"
    - "prettier --write ./**/*{.yml,.yaml,.json}"

- name: lint-fix
  module: true
  exec:
    - ./sh/lint-fix.sh
    - "golangci-lint run --timeout 10s --print-issued-lines=false --fix"

- name: test
  module: true
  env:
    - CACHE=true
    - GITHUB_OUTPUT=/dev/null
    - COVERAGE_FILE=coverage.out
    - MOD_PATH=<module>
    - PATH=<inherit>
    - HOME=<inherit>
  exec:
    - ./sh/workflows/module-pr/test-pretty.sh

- name: ci
  needs: "<git-clean>, <online>"
  exec:
    - ./sh/ci.sh

- name: ci-push
  needs: "<git-clean>, <online>"
  exec:
    - "./sh/ci.sh push"

- name: coverage
  exec:
    - ./sh/coverage.sh

- name: format-configs
  exec:
    - "prettier --write ./**/*{.yml,.yaml,.json}"

- name: generate-mocks
  exec:
    - ./sh/generate-mocks.sh

- name: spellcheck-docs
  exec:
    - "cspell --gitignore ./**/*.md"

- name: setup
  exec:
    - ./sh/setup.sh

- name: generate-go-work
  exec:
    - go run cmd/gengowork/main.go

- name: new-module
  inputs: 1
  exec:
    - ./sh/new-module.sh

- name: generate-vscode-tasks
  exec:
    - "go run cmd/genvscodetasks/main.go -module-commands <task-module-names> -repo-commands <task-not-module-names>"

- name: copyright
  exec:
    - "go run cmd/copyright/main.go"
