// Code generated by mockery. DO NOT EDIT.

package identifier

import mock "github.com/stretchr/testify/mock"

// MockRandomer is an autogenerated mock type for the Randomer type
type MockRandomer struct {
	mock.Mock
}

type MockRandomer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRandomer) EXPECT() *MockRandomer_Expecter {
	return &MockRandomer_Expecter{mock: &_m.Mock}
}

// Random provides a mock function with given fields:
func (_m *MockRandomer) Random() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Random")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockRandomer_Random_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Random'
type MockRandomer_Random_Call struct {
	*mock.Call
}

// Random is a helper method to define mock.On call
func (_e *MockRandomer_Expecter) Random() *MockRandomer_Random_Call {
	return &MockRandomer_Random_Call{Call: _e.mock.On("Random")}
}

func (_c *MockRandomer_Random_Call) Run(run func()) *MockRandomer_Random_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRandomer_Random_Call) Return(_a0 string) *MockRandomer_Random_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRandomer_Random_Call) RunAndReturn(run func() string) *MockRandomer_Random_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRandomer creates a new instance of MockRandomer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRandomer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRandomer {
	mock := &MockRandomer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
