// Code generated by mockery. DO NOT EDIT.

package httpflush

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockwriterFlusher is an autogenerated mock type for the writerFlusher type
type MockwriterFlusher struct {
	mock.Mock
}

type MockwriterFlusher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockwriterFlusher) EXPECT() *MockwriterFlusher_Expecter {
	return &MockwriterFlusher_Expecter{mock: &_m.Mock}
}

// Flush provides a mock function with given fields:
func (_m *MockwriterFlusher) Flush() {
	_m.Called()
}

// MockwriterFlusher_Flush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flush'
type MockwriterFlusher_Flush_Call struct {
	*mock.Call
}

// Flush is a helper method to define mock.On call
func (_e *MockwriterFlusher_Expecter) Flush() *MockwriterFlusher_Flush_Call {
	return &MockwriterFlusher_Flush_Call{Call: _e.mock.On("Flush")}
}

func (_c *MockwriterFlusher_Flush_Call) Run(run func()) *MockwriterFlusher_Flush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockwriterFlusher_Flush_Call) Return() *MockwriterFlusher_Flush_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockwriterFlusher_Flush_Call) RunAndReturn(run func()) *MockwriterFlusher_Flush_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function with given fields:
func (_m *MockwriterFlusher) Header() http.Header {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 http.Header
	if rf, ok := ret.Get(0).(func() http.Header); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}

	return r0
}

// MockwriterFlusher_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type MockwriterFlusher_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *MockwriterFlusher_Expecter) Header() *MockwriterFlusher_Header_Call {
	return &MockwriterFlusher_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *MockwriterFlusher_Header_Call) Run(run func()) *MockwriterFlusher_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockwriterFlusher_Header_Call) Return(_a0 http.Header) *MockwriterFlusher_Header_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockwriterFlusher_Header_Call) RunAndReturn(run func() http.Header) *MockwriterFlusher_Header_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: _a0
func (_m *MockwriterFlusher) Write(_a0 []byte) (int, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockwriterFlusher_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockwriterFlusher_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - _a0 []byte
func (_e *MockwriterFlusher_Expecter) Write(_a0 interface{}) *MockwriterFlusher_Write_Call {
	return &MockwriterFlusher_Write_Call{Call: _e.mock.On("Write", _a0)}
}

func (_c *MockwriterFlusher_Write_Call) Run(run func(_a0 []byte)) *MockwriterFlusher_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockwriterFlusher_Write_Call) Return(_a0 int, _a1 error) *MockwriterFlusher_Write_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockwriterFlusher_Write_Call) RunAndReturn(run func([]byte) (int, error)) *MockwriterFlusher_Write_Call {
	_c.Call.Return(run)
	return _c
}

// WriteHeader provides a mock function with given fields: statusCode
func (_m *MockwriterFlusher) WriteHeader(statusCode int) {
	_m.Called(statusCode)
}

// MockwriterFlusher_WriteHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteHeader'
type MockwriterFlusher_WriteHeader_Call struct {
	*mock.Call
}

// WriteHeader is a helper method to define mock.On call
//   - statusCode int
func (_e *MockwriterFlusher_Expecter) WriteHeader(statusCode interface{}) *MockwriterFlusher_WriteHeader_Call {
	return &MockwriterFlusher_WriteHeader_Call{Call: _e.mock.On("WriteHeader", statusCode)}
}

func (_c *MockwriterFlusher_WriteHeader_Call) Run(run func(statusCode int)) *MockwriterFlusher_WriteHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockwriterFlusher_WriteHeader_Call) Return() *MockwriterFlusher_WriteHeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockwriterFlusher_WriteHeader_Call) RunAndReturn(run func(int)) *MockwriterFlusher_WriteHeader_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockwriterFlusher creates a new instance of MockwriterFlusher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockwriterFlusher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockwriterFlusher {
	mock := &MockwriterFlusher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
