name: go mod check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  go-mod-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get all changed go files
        id: changed-go-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            *.go
            go.mod
            go.sum

      - name: Debug changed files
        if: true # set to false when not needed
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-go-files.outputs.all_changed_files }}
        run: |
          # print changed files to stdout
          changedArray=($ALL_CHANGED_FILES)
          echo "${#changedArray[*]} files changed"
          for file in ${changedArray[@]}; do
            echo "$file"
          done

      - name: Set up Go
        if: ${{ steps.changed-go-files.outputs.added_files_count != 0 || steps.changed-go-files.outputs.modified_files_count != 0 || steps.changed-go-files.outputs.deleted_files_count != 0 }}
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Go mod check
        if: ${{ steps.changed-go-files.outputs.added_files_count != 0 || steps.changed-go-files.outputs.modified_files_count != 0 || steps.changed-go-files.outputs.deleted_files_count != 0 }}
        uses: j0hnsmith/go-mod-check@v1
        with:
          working-directory: .
