name: main
run-name: ${{ github.head_ref }}@${{ github.sha }}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  changed-files:
    name: analyze_changed_files
    runs-on: ubuntu-latest
    outputs:
      # modules
      modClock: ${{ steps.list-changed-files.outputs.clock_all_changed_files }}
      modHttpmisc: ${{ steps.list-changed-files.outputs.httpmisc_all_changed_files }}
      modHue: ${{ steps.list-changed-files.outputs.hue_all_changed_files }}
      modIdentifier: ${{ steps.list-changed-files.outputs.identifier_all_changed_files }}
      modJsonutil: ${{ steps.list-changed-files.outputs.jsonutil_all_changed_files }}
      modLogging: ${{ steps.list-changed-files.outputs.logging_all_changed_files }}
      modMisc: ${{ steps.list-changed-files.outputs.misc_all_changed_files }}
      modCmdCopyright: ${{ steps.list-changed-files.outputs.cmd_copyright_all_changed_files }}
      modCmdGenGoWork: ${{ steps.list-changed-files.outputs.cmd_gen_go_work_all_changed_files }}
      modCmdFiler: ${{ steps.list-changed-files.outputs.cmd_filer_all_changed_files }}
      modCmdChangelog: ${{ steps.list-changed-files.outputs.cmd_changelog_all_changed_files }}
      # others
      anyGoMod: ${{ steps.list-changed-files.outputs.any_go_mod_all_changed_files }}
      rootGoMod: ${{ steps.list-changed-files.outputs.root_go_mod_all_changed_files }}
      cmdGoMod: ${{ steps.list-changed-files.outputs.cmd_go_mod_all_changed_files }}
      config: ${{ steps.list-changed-files.outputs.config_all_changed_files }}
      shell: ${{ steps.list-changed-files.outputs.shell_all_changed_files }}
      doc: ${{ steps.list-changed-files.outputs.doc_all_changed_files }}
      anyCodeAdded: ${{ steps.list-changed-files.outputs.any_code_added_files }}
      anyMod: ${{
        steps.list-changed-files.outputs.clock_all_changed_files
        || steps.list-changed-files.outputs.httpmisc_all_changed_files
        || steps.list-changed-files.outputs.hue_all_changed_files
        || steps.list-changed-files.outputs.identifier_all_changed_files
        || steps.list-changed-files.outputs.jsonutil_all_changed_files
        || steps.list-changed-files.outputs.logging_all_changed_files
        || steps.list-changed-files.outputs.misc_all_changed_files
        || steps.list-changed-files.outputs.cmd_copyright_all_changed_files
        || steps.list-changed-files.outputs.cmd_gen_go_work_all_changed_files
        || steps.list-changed-files.outputs.cmd_gen_vscode_tasks_all_changed_files
        }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Changed files
        id: list-changed-files
        uses: tj-actions/changed-files@v45.0.1
        with:
          # since_last_remote_commit: true # use only for testing, it's easy to produce no changed files
          files_yaml_from_source_file: .changed-files.yml

  debug:
    name: debug
    runs-on: ubuntu-latest
    if: false # change to debug
    env:
      HEAD_REF: ${{ github.event.pull_request.head.ref }}
      BASE_REF: ${{ github.event.pull_request.base.ref }}
    steps:
      - name: Debug
        run: true

  commitlint:
    name: commit_lint
    runs-on: ubuntu-latest
    needs: changed-files
    env:
      # will not be set when running on push/merge to main
      PR_TITLE: ${{ github.event.pull_request.title }}
      BASH_ENV: ./sh/lib/lib.sh
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          submodules: true

      - name: Create package-lock.json
        run: echo '{}' > package-lock.json

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: lts/iron
          cache: npm
      - run: |
          npm --global install @commitlint/config-conventional
          npm install --global @commitlint/cli@19.3.0
          npm install --global cspell@8.14.2

      - name: Run commitlint
        env:
          COMMITLINT_CONFIG_PATH: .commitlintrc.yml
          CSPELL_CONFIG_PATH: .cspell.config.yml
          # will not be set when running on push/merge to main
          BASE_REF: ${{ github.event.pull_request.base.ref }}
        run: ./sh/lib/workflows/main/commit_lint.sh

  root-go-mod:
    name: root_go_mod_up_to_date
    runs-on: ubuntu-latest
    needs: changed-files
    if: needs.changed-files.outputs.rootGoMod
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.23.1

      - name: Go mod
        uses: j0hnsmith/go-mod-check@v1
        with:
          working-directory: .

  cmd-go-mod:
    name: cmd_go_mod_up_to_date
    runs-on: ubuntu-latest
    needs: changed-files
    if: needs.changed-files.outputs.cmdGoMod
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.23.1

      - name: Go mod
        uses: j0hnsmith/go-mod-check@v1
        with:
          working-directory: cmd

  go-work:
    name: go_work_up_to_date
    runs-on: ubuntu-latest
    needs: changed-files
    if: false && needs.changed-files.outputs.anyGoMod
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          submodules: true

      - name: Generate go work
        run: go run cmd/gengowork/main.go

      - name: Diff
        run: ./sh/lib/workflows/main/diff.sh

  mocks:
    name: go_mocks_up_to_date
    runs-on: ubuntu-latest
    needs: changed-files
    if: needs.changed-files.outputs.anyMod1
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.23.1

      - name: Mockery
        uses: brokeyourbike/go-mockery-action@v0.1.7
        with:
          mockery-version: "2.43.0"
        env:
          BASH_ENV: ./sh/lib/lib.sh
      - run: ./sh/lib/go/generate_mocks.sh

      - name: Diff
        run: ./sh/lib/workflows/main/diff.sh

  shell:
    name: lint_format_shell
    runs-on: ubuntu-latest
    needs: changed-files
    if: needs.changed-files.outputs.shell
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Lint and format
        uses: luizm/action-sh-checker@v0.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: -d -i 2 -ln bash
          SHELLCHECK_OPTS: -x --severity=warning
        with:
          sh_checker_only_diff: true

  config:
    name: format_config
    runs-on: ubuntu-latest
    needs: changed-files
    if: needs.changed-files.outputs.config
    env:
      FILES: ${{ needs.changed-files.outputs.config }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Prettier
        uses: actionsx/prettier@v3
        with:
          args: --check ${{ env.FILES }}

  spellcheck:
    name: spellcheck
    runs-on: ubuntu-latest
    needs: changed-files
    # doesn't work on local ci, finds 0 files and gives false ok
    if: (needs.changed-files.outputs.anyCodeAdded || needs.changed-files.outputs.doc) && github.event.local != true
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Cspell
        uses: streetsidesoftware/cspell-action@v6.8.1
        with:
          files: "."
          incremental_files_only: true
          config: ./.cspell.config.yml

  copyright:
    name: copyright
    runs-on: ubuntu-latest
    needs: changed-files
    if: needs.changed-files.outputs.anyCodeAdded
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.23.1

      - name: Run Copyright
        run: |
          go run ./cmd/t0copyright -check '*.go'
          go run ./cmd/t0copyright -check '*.sh'

  ###########
  # modules #
  ###########

  clock:
    name: clock
    needs: changed-files
    if: needs.changed-files.outputs.modClock
    uses: ./.github/workflows/module_pr.yml
    with:
      goVersion: 1.23.1
      modulePath: clock

  httpmisc:
    name: httpmisc
    needs: changed-files
    if: needs.changed-files.outputs.modHttpMisc
    uses: ./.github/workflows/module_pr.yml
    with:
      goVersion: 1.23.1
      modulePath: httpmisc

  hue:
    name: hue
    needs: changed-files
    if: needs.changed-files.outputs.modHue
    uses: ./.github/workflows/module_pr.yml
    with:
      goVersion: 1.23.1
      modulePath: hue

  identifier:
    name: identifier
    needs: changed-files
    if: needs.changed-files.outputs.modIdentifier
    uses: ./.github/workflows/module_pr.yml
    with:
      goVersion: 1.23.1
      modulePath: identifier

  jsonutil:
    name: jsonutil
    needs: changed-files
    if: needs.changed-files.outputs.modJsonutil
    uses: ./.github/workflows/module_pr.yml
    with:
      goVersion: 1.23.1
      modulePath: jsonutil

  logging:
    name: logging
    needs: changed-files
    if: needs.changed-files.outputs.modLogging
    uses: ./.github/workflows/module_pr.yml
    with:
      goVersion: 1.23.1
      modulePath: logging

  misc:
    name: misc
    needs: changed-files
    if: needs.changed-files.outputs.modMisc
    uses: ./.github/workflows/module_pr.yml
    with:
      goVersion: 1.23.1
      modulePath: misc

  cmd-copyright:
    name: cmd/t0copyright
    needs: changed-files
    if: needs.changed-files.outputs.modCmdCopyright
    uses: ./.github/workflows/module_pr.yml
    with:
      goVersion: 1.23.1
      modulePath: cmd/t0copyright

  generate-go-work:
    name: cmd/gengowork
    needs: changed-files
    if: needs.changed-files.outputs.modCmdGenGoWork
    uses: ./.github/workflows/module_pr.yml
    with:
      goVersion: 1.23.1
      modulePath: cmd/gengowork

  filer:
    name: cmd/t0filer
    needs: changed-files
    if: needs.changed-files.outputs.modCmdFiler
    uses: ./.github/workflows/module_pr.yml
    with:
      goVersion: 1.23.1
      modulePath: cmd/t0filer

  cmd-changelog:
    name: cmd/t0changelog
    needs: changed-files
    if: needs.changed-files.outputs.modCmdChangelog
    uses: ./.github/workflows/module_pr.yml
    with:
      goVersion: 1.23.1
      modulePath: cmd/t0changelog
