name: Main
run-name: ${{ github.head_ref }}@${{ github.sha }}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  changed-files:
    name: Analyze changed files
    runs-on: ubuntu-latest
    outputs:
      # packages
      goPkgClock: ${{ steps.list-changed-files.outputs.pkg_clock_all_changed_files }}
      goPkgErrutil: ${{ steps.list-changed-files.outputs.pkg_errutil_all_changed_files }}
      goPkgHttpclient: ${{ steps.list-changed-files.outputs.pkg_httpclient_all_changed_files }}
      goPkgHttpflush: ${{ steps.list-changed-files.outputs.pkg_httpflush_all_changed_files }}
      goPkgHttprecoverer: ${{ steps.list-changed-files.outputs.pkg_httprecoverer_all_changed_files }}
      goPkgHttproundtrip: ${{ steps.list-changed-files.outputs.pkg_httproundtrip_all_changed_files }}
      goPkgHue: ${{ steps.list-changed-files.outputs.pkg_hue_all_changed_files }}
      goPkgIdentifier: ${{ steps.list-changed-files.outputs.pkg_identifier_all_changed_files }}
      goPkgJsonutil: ${{ steps.list-changed-files.outputs.pkg_jsonutil_all_changed_files }}
      goPkgLogging: ${{ steps.list-changed-files.outputs.pkg_logging_all_changed_files }}
      goPkgMisc: ${{ steps.list-changed-files.outputs.pkg_misc_all_changed_files }}
      goPkgReflectutil: ${{ steps.list-changed-files.outputs.pkg_reflectutil_all_changed_files }}
      # others
      goMod: ${{ steps.list-changed-files.outputs.go_mod_all_changed_files }}
      config: ${{ steps.list-changed-files.outputs.config_all_changed_files }}
      shell: ${{ steps.list-changed-files.outputs.shell_all_changed_files }}
      doc: ${{ steps.list-changed-files.outputs.doc_all_changed_files }}
      anyGoPkg: ${{
        steps.list-changed-files.outputs.pkg_clock_all_changed_files
        || steps.list-changed-files.outputs.pkg_errutil_all_changed_files
        || steps.list-changed-files.outputs.pkg_httpclient_all_changed_files
        || steps.list-changed-files.outputs.pkg_httpflush_all_changed_files
        || steps.list-changed-files.outputs.pkg_httprecoverer_all_changed_files
        || steps.list-changed-files.outputs.pkg_httproundtrip_all_changed_files
        || steps.list-changed-files.outputs.pkg_hue_all_changed_files
        || steps.list-changed-files.outputs.pkg_identifier_all_changed_files
        || steps.list-changed-files.outputs.pkg_jsonutil_all_changed_files
        || steps.list-changed-files.outputs.pkg_logging_all_changed_files
        || steps.list-changed-files.outputs.pkg_misc_all_changed_files
        || steps.list-changed-files.outputs.pkg_reflectutil_all_changed_files
        }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Changed files
        id: list-changed-files
        uses: tj-actions/changed-files@v44
        with:
          # since_last_remote_commit: true # use only for testing, it's easy to produce no changed files
          files_yaml: |
            go_mod:
              - '**/go.mod'
              - '**/go.sum'
            config:
              - '**/*.yaml'
              - '**/*.yml'
              - '**/*.json'
            doc:
              - '**/*.md'
            shell:
              - src/sh/**.sh
            pkg_clock:
              - src/clock/**.go
            pkg_errutil:
              - src/errutil/**.go
            pkg_httpclient:
              - src/httpclient/**.go
            pkg_httpflush:
              - src/httpflush/**.go
            pkg_httprecoverer:
              - src/httprecoverer/**.go
            pkg_httproundtrip:
              - src/httproundtrip/**.go
            pkg_hue:
              - src/hue/**.go
            pkg_identifier:
              - src/identifier/**.go
            pkg_jsonutil:
              - src/jsonutil/**.go
            pkg_logging:
              - src/logging/**.go
            pkg_misc:
              - src/misc/**.go
            pkg_reflectutil:
              - src/reflectutil/**.go

  debug:
    name: Debug
    runs-on: ubuntu-latest
    if: false # change to debug
    env:
      HEADREF: ${{ github.head_ref }}
      BASEREF: ${{ github.base_ref }}
    steps:
      - name: Debug
        run: true

  go-mod:
    name: Go.mod up to date
    runs-on: ubuntu-latest
    needs: changed-files
    if: needs.changed-files.outputs.anyGoPkg || needs.changed-files.outputs.goMod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Go mod
        uses: j0hnsmith/go-mod-check@v1
        with:
          working-directory: .

  mocks:
    name: Go mocks up to date
    runs-on: ubuntu-latest
    needs: changed-files
    if: needs.changed-files.outputs.anyGoPkg
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Mockery
        uses: brokeyourbike/go-mockery-action@v0
        with:
          mockery-version: "2.43.0"
      - run: ./src/sh/mocks.sh

      - name: Diff mocks
        working-directory: .
        shell: bash
        run: ./src/sh/workflows/main/diff.sh

  shell:
    name: Lint format and test shell
    runs-on: ubuntu-latest
    needs: changed-files
    if: needs.changed-files.outputs.shell
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint and format
        uses: luizm/action-sh-checker@v0.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: -d -i 2 -ln bash
          SHELLCHECK_OPTS: -x --severity=warning
        with:
          sh_checker_only_diff: true
          # needs write access https://github.com/luizm/action-sh-checker/pull/57
          # sh_checker_comment: true

      - name: Test
        run: find src/sh/sh_test -name "*-test.sh" -exec ./{} \;

  config:
    name: Format config
    runs-on: ubuntu-latest
    needs: changed-files
    if: needs.changed-files.outputs.config
    env:
      FILES: ${{ needs.changed-files.outputs.config }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prettier
        uses: hudsonm62/prettier-cli@v1.0.0
        with:
          args: --check ${{ env.FILES }}

  docs:
    name: Spellcheck docs
    runs-on: ubuntu-latest
    needs: changed-files
    # does not work locally, see CI scripts
    if: needs.changed-files.outputs.doc && github.event.local != true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cspell
        uses: streetsidesoftware/cspell-action@v6.2.0
        with:
          files: "**/*.md"
          incremental_files_only: true
          config: ./cspell.config.yaml

  clock:
    name: clock
    needs: changed-files
    if: needs.changed-files.outputs.goPkgClock
    uses: ./.github/workflows/package-pr.yml
    with:
      goVersion: 1.22
      packagePath: src/clock

  errutil:
    name: errutil
    needs: changed-files
    if: needs.changed-files.outputs.goPkgErrutil
    uses: ./.github/workflows/package-pr.yml
    with:
      goVersion: 1.22
      packagePath: src/errutil

  httpclient:
    name: httpclient
    needs: changed-files
    if: needs.changed-files.outputs.goPkgHttpclient
    uses: ./.github/workflows/package-pr.yml
    with:
      goVersion: 1.22
      packagePath: src/httpclient

  httpflush:
    name: httpflush
    needs: changed-files
    if: needs.changed-files.outputs.goPkgHttpflush
    uses: ./.github/workflows/package-pr.yml
    with:
      goVersion: 1.22
      packagePath: src/httpflush

  httprecoverer:
    name: httprecoverer
    needs: changed-files
    if: needs.changed-files.outputs.goPkgHttprecoverer
    uses: ./.github/workflows/package-pr.yml
    with:
      goVersion: 1.22
      packagePath: src/httprecoverer

  httproundtrip:
    name: httproundtrip
    needs: changed-files
    if: needs.changed-files.outputs.goPkgHttproundtrip
    uses: ./.github/workflows/package-pr.yml
    with:
      goVersion: 1.22
      packagePath: src/httproundtrip

  hue:
    name: hue
    needs: changed-files
    if: needs.changed-files.outputs.goPkgHue
    uses: ./.github/workflows/package-pr.yml
    with:
      goVersion: 1.22
      packagePath: src/hue

  identifier:
    name: identifier
    needs: changed-files
    if: needs.changed-files.outputs.goPkgIdentifier
    uses: ./.github/workflows/package-pr.yml
    with:
      goVersion: 1.22
      packagePath: src/identifier

  jsonutil:
    name: jsonutil
    needs: changed-files
    if: needs.changed-files.outputs.goPkgJsonutil
    uses: ./.github/workflows/package-pr.yml
    with:
      goVersion: 1.22
      packagePath: src/jsonutil

  logging:
    name: logging
    needs: changed-files
    if: needs.changed-files.outputs.goPkgLogging
    uses: ./.github/workflows/package-pr.yml
    with:
      goVersion: 1.22
      packagePath: src/logging

  misc:
    name: misc
    needs: changed-files
    if: needs.changed-files.outputs.goPkgMisc
    uses: ./.github/workflows/package-pr.yml
    with:
      goVersion: 1.22
      packagePath: src/misc

  reflectutil:
    name: reflectutil
    needs: changed-files
    if: needs.changed-files.outputs.goPkgReflectutil
    uses: ./.github/workflows/package-pr.yml
    with:
      goVersion: 1.22
      packagePath: src/reflectutil
